# Generated by Django 2.2.13 on 2021-12-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(choices=[('Black', 'black'), ('Brown', 'brown'), ('Yellow', 'yellow'), ('Blue', 'blue'), ('Red', 'red'), ('Green', 'green'), ('Orange', 'orange'), ('Hazel', 'hazel'), ('Pink', 'pink'), ('Gold', 'gold'), ('Purple', 'purple'), ('Unknown', 'unknown')], default='Unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(choices=[('Black', 'black'), ('Brown', 'brown'), ('Blonde', 'blonde'), ('Red', 'red'), ('White', 'white'), ('Grey', 'grey'), ('Auburn', 'auburn'), ('Bald', 'bald'), ('Unknown', 'unknown')], default='Unknown', max_length=32),
        ),
    ]
