# Generated by Django 2.2.13 on 2021-12-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211212_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('orange', 'Orange'), ('hazel', 'Hazel'), ('pink', 'Pink'), ('gold', 'Gold'), ('purple', 'Purple'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('white', 'White'), ('grey', 'Grey'), ('auburn', 'Auburn'), ('bald', 'Bald'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
    ]
